
# Reference: https://github.com/yasio/yasio/blob/main/.lgtm.yml

extraction: 
  # Define settings for C/C++ analysis
  #####################################
  cpp:
    prepare:
      packages: 
        - gettext
        - libpugixml-dev
        - cmake
        - git
        - make
    # Add an `after-prepare` step if you need to run commands after the prepare step.
    # Each command should be listed on a separate line.
    # This step is useful for C/C++ analysis where you want to prepare the environment
    # for the `configure` step without changing the default behavior for that step. 
    after_prepare:
      - export PRE_REQS_DIR=$(readlink -f .)/pre-reqs
      - git clone --branch 0.3.5 https://github.com/openSUSE/libeconf ./libeconf
      - cd libeconf
      - ./autogen.sh 
      - ./configure --prefix=/usr
      - make
      - make DESTDIR=${PRE_REQS_DIR} install
      - cd ..
      - git clone https://github.com/PerryWerneck/vmdetect.git ./vmdetect
      - cd vmdetect
      - NOCONFIGURE=1 ./autogen.sh
      - ./configure --prefix=/usr
      - make all
      - make DESTDIR=${PRE_REQS_DIR} install
      - cd ..
      - export ECONF_CFLAGS="-I${PRE_REQS_DIR}/usr/include"
      - export ECONF_LIBS="-L${PRE_REQS_DIR}/usr/lib -leconf -lm"
      - export VMDETECT_CFLAGS="-I${PRE_REQS_DIR}/usr/include"
      - export VMDETECT_LIBS="-L${PRE_REQS_DIR}/usr/lib -lvmdetect"
      - git clone https://github.com/PerryWerneck/libudjat.git ./libudjat
      - cd libudjat
      - NOCONFIGURE=1 ./autogen.sh
      - ./configure --prefix=/usr
      - make all
      - make DESTDIR=${PRE_REQS_DIR} install
      - export UDJAT_CFLAGS="-I${PRE_REQS_DIR}/usr/include"
      - export UDJAT_LIBS="-L${PRE_REQS_DIR}/usr/lib -ludjat"

